/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCollectorAddEwasteRouteImport } from './routes/_authenticated/collector/add-ewaste'
import { Route as AuthenticatedCollectorHistoryRouteImport } from './routes/_authenticated/collector/history'
import { Route as AuthenticatedCollectorHomeRouteImport } from './routes/_authenticated/collector/home'
import { Route as AuthenticatedCollectorIdentifyRouteImport } from './routes/_authenticated/collector/identify'
import { Route as AuthenticatedCollectorProfileRouteImport } from './routes/_authenticated/collector/profile'
import { Route as AuthenticatedCollectorRegisterRouteImport } from './routes/_authenticated/collector/register'
import { Route as AuthenticatedRecyclerHomeRouteImport } from './routes/_authenticated/recycler/home'
import { Route as AuthenticatedRecyclerRegisterRouteImport } from './routes/_authenticated/recycler/register'
import { Route as AuthenticatedRecyclerRequestsRouteImport } from './routes/_authenticated/recycler/requests'
import { Route as AuthenticatedRecyclerRequestIdRouteImport } from './routes/_authenticated/recycler/request.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectorAddEwasteRoute =
  AuthenticatedCollectorAddEwasteRouteImport.update({
    id: '/collector/add-ewaste',
    path: '/collector/add-ewaste',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorHistoryRoute =
  AuthenticatedCollectorHistoryRouteImport.update({
    id: '/collector/history',
    path: '/collector/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorHomeRoute =
  AuthenticatedCollectorHomeRouteImport.update({
    id: '/collector/home',
    path: '/collector/home',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorIdentifyRoute =
  AuthenticatedCollectorIdentifyRouteImport.update({
    id: '/collector/identify',
    path: '/collector/identify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorProfileRoute =
  AuthenticatedCollectorProfileRouteImport.update({
    id: '/collector/profile',
    path: '/collector/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorRegisterRoute =
  AuthenticatedCollectorRegisterRouteImport.update({
    id: '/collector/register',
    path: '/collector/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerHomeRoute =
  AuthenticatedRecyclerHomeRouteImport.update({
    id: '/recycler/home',
    path: '/recycler/home',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerRegisterRoute =
  AuthenticatedRecyclerRegisterRouteImport.update({
    id: '/recycler/register',
    path: '/recycler/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerRequestsRoute =
  AuthenticatedRecyclerRequestsRouteImport.update({
    id: '/recycler/requests',
    path: '/recycler/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerRequestIdRoute =
  AuthenticatedRecyclerRequestIdRouteImport.update({
    id: '/recycler/request/$id',
    path: '/recycler/request/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collector/add-ewaste': typeof AuthenticatedCollectorAddEwasteRoute
  '/collector/history': typeof AuthenticatedCollectorHistoryRoute
  '/collector/home': typeof AuthenticatedCollectorHomeRoute
  '/collector/identify': typeof AuthenticatedCollectorIdentifyRoute
  '/collector/profile': typeof AuthenticatedCollectorProfileRoute
  '/collector/register': typeof AuthenticatedCollectorRegisterRoute
  '/recycler/home': typeof AuthenticatedRecyclerHomeRoute
  '/recycler/register': typeof AuthenticatedRecyclerRegisterRoute
  '/recycler/requests': typeof AuthenticatedRecyclerRequestsRoute
  '/recycler/request/$id': typeof AuthenticatedRecyclerRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collector/add-ewaste': typeof AuthenticatedCollectorAddEwasteRoute
  '/collector/history': typeof AuthenticatedCollectorHistoryRoute
  '/collector/home': typeof AuthenticatedCollectorHomeRoute
  '/collector/identify': typeof AuthenticatedCollectorIdentifyRoute
  '/collector/profile': typeof AuthenticatedCollectorProfileRoute
  '/collector/register': typeof AuthenticatedCollectorRegisterRoute
  '/recycler/home': typeof AuthenticatedRecyclerHomeRoute
  '/recycler/register': typeof AuthenticatedRecyclerRegisterRoute
  '/recycler/requests': typeof AuthenticatedRecyclerRequestsRoute
  '/recycler/request/$id': typeof AuthenticatedRecyclerRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/collector/add-ewaste': typeof AuthenticatedCollectorAddEwasteRoute
  '/_authenticated/collector/history': typeof AuthenticatedCollectorHistoryRoute
  '/_authenticated/collector/home': typeof AuthenticatedCollectorHomeRoute
  '/_authenticated/collector/identify': typeof AuthenticatedCollectorIdentifyRoute
  '/_authenticated/collector/profile': typeof AuthenticatedCollectorProfileRoute
  '/_authenticated/collector/register': typeof AuthenticatedCollectorRegisterRoute
  '/_authenticated/recycler/home': typeof AuthenticatedRecyclerHomeRoute
  '/_authenticated/recycler/register': typeof AuthenticatedRecyclerRegisterRoute
  '/_authenticated/recycler/requests': typeof AuthenticatedRecyclerRequestsRoute
  '/_authenticated/recycler/request/$id': typeof AuthenticatedRecyclerRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collector/add-ewaste'
    | '/collector/history'
    | '/collector/home'
    | '/collector/identify'
    | '/collector/profile'
    | '/collector/register'
    | '/recycler/home'
    | '/recycler/register'
    | '/recycler/requests'
    | '/recycler/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collector/add-ewaste'
    | '/collector/history'
    | '/collector/home'
    | '/collector/identify'
    | '/collector/profile'
    | '/collector/register'
    | '/recycler/home'
    | '/recycler/register'
    | '/recycler/requests'
    | '/recycler/request/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/collector/add-ewaste'
    | '/_authenticated/collector/history'
    | '/_authenticated/collector/home'
    | '/_authenticated/collector/identify'
    | '/_authenticated/collector/profile'
    | '/_authenticated/collector/register'
    | '/_authenticated/recycler/home'
    | '/_authenticated/recycler/register'
    | '/_authenticated/recycler/requests'
    | '/_authenticated/recycler/request/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collector/add-ewaste': {
      id: '/_authenticated/collector/add-ewaste'
      path: '/collector/add-ewaste'
      fullPath: '/collector/add-ewaste'
      preLoaderRoute: typeof AuthenticatedCollectorAddEwasteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/history': {
      id: '/_authenticated/collector/history'
      path: '/collector/history'
      fullPath: '/collector/history'
      preLoaderRoute: typeof AuthenticatedCollectorHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/home': {
      id: '/_authenticated/collector/home'
      path: '/collector/home'
      fullPath: '/collector/home'
      preLoaderRoute: typeof AuthenticatedCollectorHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/identify': {
      id: '/_authenticated/collector/identify'
      path: '/collector/identify'
      fullPath: '/collector/identify'
      preLoaderRoute: typeof AuthenticatedCollectorIdentifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/profile': {
      id: '/_authenticated/collector/profile'
      path: '/collector/profile'
      fullPath: '/collector/profile'
      preLoaderRoute: typeof AuthenticatedCollectorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/register': {
      id: '/_authenticated/collector/register'
      path: '/collector/register'
      fullPath: '/collector/register'
      preLoaderRoute: typeof AuthenticatedCollectorRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/home': {
      id: '/_authenticated/recycler/home'
      path: '/recycler/home'
      fullPath: '/recycler/home'
      preLoaderRoute: typeof AuthenticatedRecyclerHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/register': {
      id: '/_authenticated/recycler/register'
      path: '/recycler/register'
      fullPath: '/recycler/register'
      preLoaderRoute: typeof AuthenticatedRecyclerRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/requests': {
      id: '/_authenticated/recycler/requests'
      path: '/recycler/requests'
      fullPath: '/recycler/requests'
      preLoaderRoute: typeof AuthenticatedRecyclerRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/request/$id': {
      id: '/_authenticated/recycler/request/$id'
      path: '/recycler/request/$id'
      fullPath: '/recycler/request/$id'
      preLoaderRoute: typeof AuthenticatedRecyclerRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectorAddEwasteRoute: typeof AuthenticatedCollectorAddEwasteRoute
  AuthenticatedCollectorHistoryRoute: typeof AuthenticatedCollectorHistoryRoute
  AuthenticatedCollectorHomeRoute: typeof AuthenticatedCollectorHomeRoute
  AuthenticatedCollectorIdentifyRoute: typeof AuthenticatedCollectorIdentifyRoute
  AuthenticatedCollectorProfileRoute: typeof AuthenticatedCollectorProfileRoute
  AuthenticatedCollectorRegisterRoute: typeof AuthenticatedCollectorRegisterRoute
  AuthenticatedRecyclerHomeRoute: typeof AuthenticatedRecyclerHomeRoute
  AuthenticatedRecyclerRegisterRoute: typeof AuthenticatedRecyclerRegisterRoute
  AuthenticatedRecyclerRequestsRoute: typeof AuthenticatedRecyclerRequestsRoute
  AuthenticatedRecyclerRequestIdRoute: typeof AuthenticatedRecyclerRequestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectorAddEwasteRoute: AuthenticatedCollectorAddEwasteRoute,
  AuthenticatedCollectorHistoryRoute: AuthenticatedCollectorHistoryRoute,
  AuthenticatedCollectorHomeRoute: AuthenticatedCollectorHomeRoute,
  AuthenticatedCollectorIdentifyRoute: AuthenticatedCollectorIdentifyRoute,
  AuthenticatedCollectorProfileRoute: AuthenticatedCollectorProfileRoute,
  AuthenticatedCollectorRegisterRoute: AuthenticatedCollectorRegisterRoute,
  AuthenticatedRecyclerHomeRoute: AuthenticatedRecyclerHomeRoute,
  AuthenticatedRecyclerRegisterRoute: AuthenticatedRecyclerRegisterRoute,
  AuthenticatedRecyclerRequestsRoute: AuthenticatedRecyclerRequestsRoute,
  AuthenticatedRecyclerRequestIdRoute: AuthenticatedRecyclerRequestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
